# Generated by Django 6.0.5 on 2026-05-26 07:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('kitchen_type', models.CharField(choices=[('main', 'Main Kitchen'), ('prep', 'Prep Kitchen'), ('dessert', 'Dessert Kitchen'), ('bar', 'Bar'), ('custom', 'Custom')], default='main', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kitchen',
                'verbose_name_plural': 'Kitchens',
                'db_table': 'kds_kitchen',
            },
        ),
        migrations.CreateModel(
            name='KitchenAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('ready', 'Item Ready'), ('delay', 'Order Delayed'), ('new_order', 'New Order'), ('custom', 'Custom Alert')], default='custom', max_length=20)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='kitchen_display_system.kitchen')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_alerts', to='orders.order')),
            ],
            options={
                'verbose_name': 'Kitchen Alert',
                'verbose_name_plural': 'Kitchen Alerts',
                'db_table': 'kds_kitchen_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='kitchen_display_system.kitchen')),
            ],
            options={
                'verbose_name': 'Kitchen Department',
                'verbose_name_plural': 'Kitchen Departments',
                'db_table': 'kds_kitchen_department',
                'ordering': ['display_order'],
                'unique_together': {('kitchen', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KitchenDisplaySystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('enable_sound_alerts', models.BooleanField(default=True)),
                ('enable_ready_alerts', models.BooleanField(default=True)),
                ('auto_kot_printing', models.BooleanField(default=True)),
                ('preparation_time_default', models.IntegerField(default=15, help_text='Default preparation time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kds_systems', to='authentication.branch')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_display_system', to='authentication.restaurant')),
            ],
            options={
                'verbose_name': 'Kitchen Display System',
                'verbose_name_plural': 'Kitchen Display Systems',
                'db_table': 'kds_kitchen_display_system',
            },
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to='kitchen_display_system.kitchendisplaysystem'),
        ),
        migrations.CreateModel(
            name='KitchenOrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen_display_system.kitchendepartment')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen_display_system.kitchen')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Kitchen Order Status',
                'verbose_name_plural': 'Kitchen Order Status',
                'db_table': 'kds_kitchen_order_status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenOrderTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kot_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('reprinted', 'Reprinted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('print_count', models.IntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen_display_system.kitchendepartment')),
                ('items', models.ManyToManyField(related_name='kots', to='orders.orderitem')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='kitchen_display_system.kitchen')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='orders.order')),
            ],
            options={
                'verbose_name': 'Kitchen Order Ticket',
                'verbose_name_plural': 'Kitchen Order Tickets',
                'db_table': 'kds_kitchen_order_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_priority', to='orders.order')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Priority',
                'verbose_name_plural': 'Order Priorities',
                'db_table': 'kds_order_priority',
            },
        ),
        migrations.CreateModel(
            name='PreparationTimer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_duration', models.IntegerField(default=15, help_text='Estimated duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=True)),
                ('kitchen_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='kitchen_display_system.kitchenorderstatus')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_timers', to='orders.order')),
            ],
            options={
                'verbose_name': 'Preparation Timer',
                'verbose_name_plural': 'Preparation Timers',
                'db_table': 'kds_preparation_timer',
            },
        ),
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('thermal', 'Thermal Printer'), ('inkjet', 'Inkjet Printer'), ('laser', 'Laser Printer')], default='thermal', max_length=20)),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('bluetooth', 'Bluetooth'), ('lan', 'LAN'), ('wifi', 'WiFi'), ('serial', 'Serial')], default='usb', max_length=20)),
                ('printer_address', models.CharField(help_text='IP address or device address', max_length=255)),
                ('port_number', models.IntegerField(blank=True, default=9100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('paper_width', models.IntegerField(default=80, help_text='Paper width in mm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen_display_system.kitchendepartment')),
                ('kds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='kitchen_display_system.kitchendisplaysystem')),
            ],
            options={
                'verbose_name': 'Printer Configuration',
                'verbose_name_plural': 'Printer Configurations',
                'db_table': 'kds_printer_configuration',
            },
        ),
        migrations.CreateModel(
            name='KOTPrintLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('print_type', models.CharField(choices=[('initial', 'Initial Print'), ('reprint', 'Reprint')], default='initial', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='kitchen_display_system.kitchenorderticket')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen_display_system.printerconfiguration')),
            ],
            options={
                'verbose_name': 'KOT Print Log',
                'verbose_name_plural': 'KOT Print Logs',
                'db_table': 'kds_kot_print_log',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='kitchen',
            unique_together={('kds', 'name')},
        ),
    ]
