# Generated by Django 6.0.5 on 2026-05-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
