# Generated by Django 6.0.5 on 2026-05-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('total_orders', models.IntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
