# Generated by Django 6.0.5 on 2026-05-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0009_orderreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
