# Generated by Django 6.0.5 on 2026-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0010_taxrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
    ]
