# Generated by Django 6.0.5 on 2026-05-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0011_inventoryreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('orders_handled', models.IntegerField()),
                ('revenue_generated', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
