# Generated by Django 6.0.5 on 2026-05-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0012_employeereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('total_orders', models.IntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
