# Generated by Django 6.0.5 on 2026-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0013_customerreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
