# Generated by Django 6.0.5 on 2026-05-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0014_cancellationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
