from django.urls import path
from .views import (
    SalesReportListCreateView,
    ProductListCreateView,
    MonthlyReportView,
    ChartDataView,
    TopSellingItemsView,
    PeakHoursView,
    BranchPerformanceView,
    StaffPerformanceView,
    CustomerAnalyticsView,
    InventoryInsightsView,
    ProfitAnalyticsView,
    OrderReportView,
    TaxReportView,
    InventoryReportView,
    EmployeeReportView,
    CustomerReportView,
    CancellationReportView,
    DiscountReportView,
    export_pdf,
    export_excel,
    export_csv,
    employee_list,
    inventory_list,
    customer_list,
    dashboard
)

urlpatterns = [
    path('sales/', SalesReportListCreateView.as_view(), name='sales-list'),
    path('products/', ProductListCreateView.as_view(), name='products-list'),
    path('dashboard/', dashboard, name='dashboard'),
    path('monthly-report/', MonthlyReportView.as_view(), name='monthly-report'),
    path('chart-data/', ChartDataView.as_view(), name='chart-data'),
    path('top-selling-items/', TopSellingItemsView.as_view(), name='top-selling-items'),
    path('peak-hours/', PeakHoursView.as_view(), name='peak-hours'),
    path('branch-performance/', BranchPerformanceView.as_view(), name='branch-performance'),
    path( 'staff-performance/', StaffPerformanceView.as_view(), name='staff-performance'),
    path('customer-analytics/', CustomerAnalyticsView.as_view(), name='customer-analytics'),
    path('inventory-insights/', InventoryInsightsView.as_view(), name='inventory-insights'),
    path('profit-analytics/', ProfitAnalyticsView.as_view(), name='profit-analytics'),
    path('order-report/', OrderReportView.as_view(), name='order-report'),
    path('tax-report/', TaxReportView.as_view(), name='tax-report'),
    path('inventory-report/', InventoryReportView.as_view(),  name='inventory-report'),
    path('employee-report/',  EmployeeReportView.as_view(), name='employee-report'),
    path( 'customer-report/', CustomerReportView.as_view(), name='customer-report'),
    path( 'cancellation-report/', CancellationReportView.as_view(), name='cancellation-report'),
    path('discount-report/', DiscountReportView.as_view(), name='discount-report'),
    path('export/pdf/', export_pdf, name='export-pdf'),
    path( 'export/excel/', export_excel, name='export-excel'),
    path( 'export/csv/', export_csv, name='export-csv'),
    path("employee-list/",employee_list),
    path( "inventory-list/",inventory_list),
    path("customer-list/", customer_list),
]