# Generated by Django 5.2.11 on 2026-05-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_attendance_method_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_from', to='hr.shift')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='hr.employee')),
                ('requested_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_to', to='hr.shift')),
            ],
        ),
    ]
