# Generated by Copilot to restore the missing billing schema dependency.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=100)),
                ("service_charge_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="authentication.restaurant"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cgst_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("sgst_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("igst_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tax_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.taxprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64, unique=True)),
                ("discount_type", models.CharField(choices=[("PERCENT", "Percent"), ("FIXED", "Fixed")], max_length=10)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("usage_limit", models.IntegerField(blank=True, null=True)),
                ("per_customer_limit", models.IntegerField(blank=True, null=True)),
                ("min_order_value", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("restaurant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="authentication.restaurant")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.branch")),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.table",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.customer",
                    ),
                ),
                ("order_type", models.CharField(choices=[("DINEIN", "Dine In"), ("TAKEAWAY", "Takeaway"), ("DELIVERY", "Delivery")], max_length=20)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("HELD", "Held"), ("CLOSED", "Closed"), ("CANCELLED", "Cancelled")], default="OPEN", max_length=20)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("service_charge", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("net_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("modifiers", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("NEW", "New"), ("PREPARING", "Preparing"), ("SERVED", "Served"), ("VOIDED", "Voided")], default="NEW", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("menu_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="billing.menuitem")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="billing.order")),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("mode", models.CharField(choices=[("CASH", "Cash"), ("CARD", "Card"), ("UPI", "UPI"), ("WALLET", "Wallet"), ("OTHER", "Other")], max_length=20)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="billing.order"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="billing.payment"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
