# Generated by Django 5.2.14 on 2026-05-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=128)),
                ('entity', models.CharField(max_length=128)),
                ('entity_id', models.CharField(blank=True, max_length=128, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"django_schema"."audit_logs"',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('visit_count', models.IntegerField(default=0)),
                ('preferred_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"django_schema"."customers"',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, max_length=64, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=64, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': '"django_schema"."delivery_riders"',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('designation', models.CharField(blank=True, max_length=128, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=64, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"django_schema"."employees"',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('category', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"django_schema"."expenses"',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=64, null=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"django_schema"."inventory_items"',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.IntegerField()),
                ('tier_name', models.CharField(max_length=64)),
                ('min_points', models.IntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('benefits', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': '"django_schema"."loyalty_tiers"',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('po_number', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ordered_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"django_schema"."purchase_orders"',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"django_schema"."suppliers"',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(max_length=32)),
                ('otp', models.CharField(blank=True, max_length=16, null=True)),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.JSONField(blank=True, default=dict)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_schema.deliveryrider')),
            ],
            options={
                'db_table': '"django_schema"."deliveries"',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=32, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.employee')),
            ],
            options={
                'db_table': '"django_schema"."attendance"',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=64)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.employee')),
            ],
            options={
                'db_table': '"django_schema"."leave_requests"',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=32)),
                ('points', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='django_schema.customer')),
            ],
            options={
                'db_table': '"django_schema"."loyalty_points"',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incentives', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.employee')),
            ],
            options={
                'db_table': '"django_schema"."payroll"',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_schema.purchaseorder')),
            ],
            options={
                'db_table': '"django_schema"."purchase_order_items"',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_item_id', models.IntegerField()),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=32)),
                ('inventory_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.inventoryitem')),
            ],
            options={
                'db_table': '"django_schema"."recipes"',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.inventoryitem')),
            ],
            options={
                'db_table': '"django_schema"."stock_movements"',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.supplier'),
        ),
        migrations.CreateModel(
            name='WastageLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('logged_by', models.IntegerField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_schema.inventoryitem')),
            ],
            options={
                'db_table': '"django_schema"."wastage_logs"',
            },
        ),
    ]
