# Generated by Django 5.2.14 on 2026-05-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_id', models.CharField(blank=True, max_length=64, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('billing_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('aggregator', 'Aggregator')], default='web', max_length=32)),
                ('delivery_type', models.CharField(choices=[('dinein', 'Dine-in'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=32)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_contact', models.CharField(blank=True, max_length=64, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='pinesphere_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu_item_id', models.CharField(blank=True, max_length=64, null=True)),
                ('menu_item_snapshot', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('modifiers', models.JSONField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pinesphere_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pinesphere_orders.order')),
            ],
        ),
    ]
