# Generated by Django 5.2.14 on 2026-05-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shift',
            new_name='pos_shift_restaur_aab0a5_idx',
            old_name='pos_shift_restaurant_id_idx',
        ),
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='pos_staffme_restaur_259d83_idx',
            old_name='pos_staffmember_restaurant_id_idx',
        ),
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='pos_staffme_restaur_499ad8_idx',
            old_name='pos_staffmember_restaurant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='pos_staffme_restaur_f60ed1_idx',
            old_name='pos_staffmember_restaurant_role_idx',
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['restaurant_id'], name='pos_role_restaur_6d1439_idx'),
        ),
    ]
