# Generated by Django 5.2.14 on 2026-05-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_menu_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cart',
            new_name='pos_cart_user_id_7ab2e7_idx',
            old_name='pos_cart_user_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='pos_cartite_cart_id_8a1a04_idx',
            old_name='pos_cartitem_cart_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='pos_cartite_menu_it_138d6e_idx',
            old_name='pos_cartitem_menu_item_id_idx',
        ),
        migrations.RenameIndex(
            model_name='menucategory',
            new_name='pos_menucat_restaur_931b5d_idx',
            old_name='pos_menucat_restaurant_id_idx',
        ),
        migrations.RenameIndex(
            model_name='menucategory',
            new_name='pos_menucat_restaur_f670f9_idx',
            old_name='pos_menucat_restaurant_name_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='pos_menuite_restaur_5887b5_idx',
            old_name='pos_menuitem_restaurant_id_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='pos_menuite_restaur_25f202_idx',
            old_name='pos_menuitem_restaurant_category_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='pos_menuite_restaur_a358b7_idx',
            old_name='pos_menuitem_restaurant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='pos_menuite_restaur_043654_idx',
            old_name='pos_menuitem_restaurant_name_idx',
        ),
    ]
