# Generated by Django 5.2.14 on 2026-05-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_shift_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='color',
            field=models.CharField(blank=True, default='slate', max_length=32),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='kds_station_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='parent_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
