from django.urls import path

from .views import (
    integrations_view,
    integration_disconnect_view,
    integration_provider_view,
    kds_station_detail_view,
    kds_stations_list_view,
    menu_categories_create_view,
    menu_categories_list_view,
    menu_categories_reorder_view,
    menu_category_detail_view,
    notifications_settings_view,
    payment_settings_view,
    permissions_list_view,
    printer_detail_view,
    printer_test_view,
    printers_list_view,
    restaurant_cover_photo_upload_view,
    restaurant_logo_upload_view,
    restaurant_settings_view,
    role_detail_view,
    roles_list_view,
    security_settings_view,
    shift_coverage_view,
    shift_detail_view,
    shifts_list_view,
    tax_rate_detail_view,
    tax_rates_list_view,
)

urlpatterns = [
    path("restaurant/", restaurant_settings_view, name="restaurant-settings"),
    path("restaurant/logo/", restaurant_logo_upload_view, name="restaurant-settings-logo"),
    path("restaurant/cover-photo/", restaurant_cover_photo_upload_view, name="restaurant-settings-cover-photo"),
    path("permissions/", permissions_list_view, name="settings-permissions"),
    path("roles/", roles_list_view, name="settings-roles"),
    path("roles/<int:role_id>/", role_detail_view, name="settings-role-detail"),
    path("menu-categories/", menu_categories_list_view, name="settings-menu-categories"),
    path("menu-categories/reorder/", menu_categories_reorder_view, name="settings-menu-categories-reorder"),
    path("menu-categories/create/", menu_categories_create_view, name="settings-menu-categories-create"),
    path("menu-categories/<uuid:category_id>/", menu_category_detail_view, name="settings-menu-category-detail"),
    path("kds-stations/", kds_stations_list_view, name="settings-kds-stations"),
    path("kds-stations/<uuid:station_id>/", kds_station_detail_view, name="settings-kds-station-detail"),
    path("shifts/", shifts_list_view, name="settings-shifts"),
    path("shifts/coverage/", shift_coverage_view, name="settings-shift-coverage"),
    path("shifts/<int:shift_id>/", shift_detail_view, name="settings-shift-detail"),
    path("printers/", printers_list_view, name="settings-printers"),
    path("printers/<uuid:printer_id>/", printer_detail_view, name="settings-printer-detail"),
    path("printers/<uuid:printer_id>/test/", printer_test_view, name="settings-printer-test"),
    path("payment/", payment_settings_view, name="settings-payment"),
    path("tax-rates/", tax_rates_list_view, name="settings-tax-rates"),
    path("tax-rates/<uuid:tax_rate_id>/", tax_rate_detail_view, name="settings-tax-rate-detail"),
    path("notifications/", notifications_settings_view, name="settings-notifications"),
    path("security/", security_settings_view, name="settings-security"),
    path("integrations/", integrations_view, name="settings-integrations"),
    path("integrations/<str:provider>/", integration_provider_view, name="settings-integration-provider"),
    path("integrations/<str:provider>/connect/", integration_provider_view, name="settings-integration-connect"),
    path("integrations/<str:provider>/disconnect/", integration_disconnect_view, name="settings-integration-disconnect"),
]
